delete from employee;
delete from company;
INSERT INTO company(company_name) VALUES ('00CL');
INSERT INTO employee(name, age, gender, salary, company_id) VALUES ('Bob Smith', 10, 'Male', 1000, 1);
INSERT INTO employee(name, age, gender, salary, company_id) VALUES ('Tom Green', 20, 'Female', 1000, 1);
INSERT INTO employee(name, age, gender, salary, company_id) VALUES ('Will Smith', 30, 'Male', 1000, 1);
INSERT INTO employee(name, age, gender, salary, company_id) VALUES ('Tom Green', 20, 'Female', 1000, 1);
INSERT INTO employee(name, age, gender, salary, company_id) VALUES ('Will Smith', 30, 'Male', 1000, 1);
INSERT INTO employee(name, age, gender, salary, company_id) VALUES ('Billy Butcher', 40, 'Male', 1000, 1);
INSERT INTO employee(name, age, gender, salary, company_id) VALUES ('Star Light', 50, 'Female', 1000, 1);
INSERT INTO employee(name, age, gender, salary, company_id) VALUES ('The Homelander', 60, 'Male', 1000, 1);
INSERT INTO employee(name, age, gender, salary, company_id) VALUES ('John Snow', 70, 'Male', 1000, 1);